---
title: "Data_visualization"
author: "Adelaide Robinson"
date: '2022-08-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(patchwork)
library(ggrepel)
library(gghighlight)
#library(palletteer)
library(ggextra)
library(ggbeeswarm)
library(gapminder)
#library sf

```


```{r}
lizards <- read_csv(here("data_tidy", "lizards.csv"))
```


```{r}
lizards |> ggplot(aes(x = total_length, y = weight)) + 
  geom_point()
# geom_point can change to any compatable type
```

```{r}
lizards |> ggplot(aes(x = total_length)) + 
  geom_histogram(color = "orange",
                 size = 0.3,
                 fill = "purple",
                 linetype = "dotted"
                 )
#changes aesthetic not based on variable, don't put w/in aes

```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight))+
  geom_point(
  shape = 22,
  color = "cyan 4",
  fill= "yellow",
  size = 4,
  alpha = 0.4,
)
```

```{r}
ggplot(data = lizards,
       aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name, size = total_length),
             alpha = 0.5) +
  facet_wrap(~common_name,
             scales = "free") #change the scales
  theme_minimal()

```

total counts of lizards by common name

```{r}

new_lizard <- lizards |> 
  group_by(common_name) |> 
  summarize(
    counts = n()
  )
# do it using counts
lizard_counts <- lizards |> 
  count(common_name)

```

# plot it
#default is alphabetical order 
```{r}
ggplot(data = lizard_counts, 
       aes(y = fct_reorder(common_name, n),# reorder common names by number
           x = n)) +
  geom_col()
#we want to change the order
```

create a scatterplot, faceted by species, for total length vs weight
the color and shape of points should differ based on the species
change the theme, make each faceted panel have flexible axes limits(scale is free)
```{r}
lizards |> 
  ggplot(aes(x = weight, y = total_length)) + 
  geom_point(aes(color = common_name, shape = common_name)) +
  facet_wrap(~common_name, scale = "free")
```

